APPLY_FIXES: none
DISABLE:
  - RUST
  - R
DISABLE_LINTERS:
  - C_CPPLINT
  - CSS_STYLELINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
