version: "3"

env:
  NOT_CRAN: "true"
  LIBR_POLARS_BUILD: "true"
  DEBUG: "true"

vars:
  REQUIRED_R_PKGS_FOR_S3_METHODS: tibble

  MANIFEST: src/rust/Cargo.toml
  CARGO_LOCK: src/rust/Cargo.lock
  R_SOURCE: R/*
  R_TESTS: tests/*
  VIGNETTES: vignettes/**/*.Rmd
  RUST_SOURCE: src/rust/src/**/*.rs

  R_FUNC_LOAD_REQUIRED_PKGS:
    strsplit("{{.REQUIRED_R_PKGS_FOR_S3_METHODS}}", ",") |>
      unlist() |>
      lapply(require, character.only = TRUE) |>
      invisible()

# TODO: setup tools
# TODO: lint, auto format

tasks:
  setup-dev:
    desc: Install tools for development.
    deps:
      - setup-r-tools
      - setup-rust-tools

  setup-r-tools:
    env:
      PKG_SYSREQS: FALSE
    desc: Install R packages for development.
    cmds:
      - Rscript -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'
      - Rscript -e
        'pak::repo_add("https://cloud.r-project.org/");
        pak::local_install_deps(dependencies = c("all", "Config/Needs/dev", "Config/Needs/website"))'

  setup-rust-tools:
    desc: Install Rust tools for development.
    cmds:
      # TODO: check the savvy version
      - cargo install savvy-cli

  build-rust:
    desc: Build the Rust library wrappers.
    aliases:
      - br
    sources:
      - src/Makevars*
      - configure*
      - "{{.MANIFEST}}"
      - "{{.CARGO_LOCK}}"
      - "{{.RUST_SOURCE}}"
    generates:
      - R/000-wrappers.R
    deps:
      - format-rust
    cmds:
      - savvy-cli update .
      - Rscript -e 'pkgbuild::compile_dll()'

  build-standalone-files:
    desc: Update "standalone" R files by `usethis::use_standalone()`
    ignore_error: true # GitHub API rate limit
    generates:
      - R/import-standalone-*.R
    vars:
      RLANG_STANDALONE_FILES:
        - lifecycle
        - s3-register
        - types-check
    cmds:
      - for:
          var: RLANG_STANDALONE_FILES
        cmd: Rscript -e 'usethis::use_standalone("r-lib/rlang", "{{.ITEM}}")'

  build-documents:
    desc: Build the R package and generate documents.
    aliases:
      - bd
    sources:
      - DESCRIPTION
      - "{{.R_SOURCE}}"
    generates:
      - man/*.Rd
    status:
      - Rscript -e 'if (desc::desc_get("RoxygenNote") < packageVersion("roxygen2")) quit(status = 1)'
    deps:
      - build-rust
      - build-standalone-files
      - format-r
    cmds:
      - Rscript -e
        '{{.R_FUNC_LOAD_REQUIRED_PKGS}};
        devtools::document()'

  build-all:
    desc: Build the R package, generate documents, run all tests, and update files.
    deps:
      - build-documents
    cmds:
      - task: test-all
      - task: build-readme

  test-all:
    desc: Run all tests.
    cmds:
      - task: test-source

  test-source:
    desc: Run all tests for source.
    internal: true
    sources:
      - tests/**/*
      - "{{.R_SOURCE}}"
      - src/Makevars*
      - configure*
      - "{{.MANIFEST}}"
      - "{{.CARGO_LOCK}}"
      - "{{.RUST_SOURCE}}"
    cmds:
      - Rscript -e 'devtools::test()'

  build-readme:
    internal: true
    desc: Build README.md
    sources:
      - README.Rmd
      - "{{.R_SOURCE}}"
      - src/Makevars*
      - configure*
      - "{{.MANIFEST}}"
      - "{{.CARGO_LOCK}}"
      - "{{.RUST_SOURCE}}"
    generates:
      - README.md
    deps:
      - build-rust
    cmds:
      - Rscript -e
        'devtools::load_all();
        rmarkdown::render(input = "README.Rmd", output_file = "README.md")'

  install-package:
    desc: Install the R package.
    sources:
      - DESCRIPTION
      - "{{.R_SOURCE}}"
      - src/Makevars*
      - configure*
      - "{{.MANIFEST}}"
      - "{{.CARGO_LOCK}}"
      - "{{.RUST_SOURCE}}"
    deps:
      - build-documents
    cmds:
      - R CMD INSTALL --no-multiarch --with-keep.source .

  test-snapshot-accept:
    desc: Accept all test snapshots. (Shortcut to accept snapshots after running tests)
    cmds:
      - Rscript -e 'testthat::snapshot_accept()'

  format-all:
    desc: Format all files.
    aliases:
      - fmt
      - fmt-all
    deps:
      - format-r
      - format-rust

  format-r:
    desc: Format R files.
    aliases:
      - fmt-r
    sources:
      - "{{.R_SOURCE}}"
      - "{{.R_TESTS}}"
      - air.toml
      # These files are auto-generated and ignored by the formatter
      - exclude: R/000-wrappers.R
      - exclude: R/import-standalone-*.R
    generates:
      - "{{.R_SOURCE}}"
      - "{{.R_TESTS}}"
      - exclude: R/000-wrappers.R
      - exclude: R/import-standalone-*.R
    cmds:
      - air format R/ tests/

  format-rust:
    desc: Format Rust files.
    aliases:
      - fmt-rust
    sources:
      - "{{.RUST_SOURCE}}"
      - "{{.MANIFEST}}"
    generates:
      - "{{.RUST_SOURCE}}"
    cmds:
      - cargo fmt --all --manifest-path {{.MANIFEST}}
