[package]
name = "r-polars"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib", "lib"]

[profile.release]
panic = "unwind"

[dependencies]
savvy = "0.6.4"
polars-core = { git = "https://github.com/pola-rs/polars.git", rev = "f73937ab5213a44eaaba8cfc799d8f837600f179", default-features = false }
polars-error = { git = "https://github.com/pola-rs/polars.git", rev = "f73937ab5213a44eaaba8cfc799d8f837600f179", default-features = false }
thiserror = "1"

[dependencies.polars]
git = "https://github.com/pola-rs/polars.git"
rev = "f73937ab5213a44eaaba8cfc799d8f837600f179"
features = [
    "dtype-full",
    "lazy",
    "meta",
    "propagate_nans",
    "temporal",
    "timezones",
]
