[package]
name = "r-polars"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib", "lib"]

[profile.release]
panic = "unwind"

[dependencies]
ciborium = "0.2"
polars-core = { git = "https://github.com/pola-rs/polars.git", rev = "7686025ac7738607f2d4f6887e9a1313b7c8b1e2", default-features = false }
polars-error = { git = "https://github.com/pola-rs/polars.git", rev = "7686025ac7738607f2d4f6887e9a1313b7c8b1e2", default-features = false }
savvy = "0.6.4"
serde_json = "1"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1"

[dependencies.polars]
git = "https://github.com/pola-rs/polars.git"
rev = "7686025ac7738607f2d4f6887e9a1313b7c8b1e2"
features = [
    "binary_encoding",
    "dtype-full",
    "json",
    "lazy",
    "meta",
    "parquet",
    "propagate_nans",
    "serde",
    "serde-lazy",
    "temporal",
    "timezones",
]
