name: Build WASM
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - configure*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy rust-toolchain.toml
        # r-wasm/actions/build-rwasm@main does not execute the bootstrap.R script
        run: |
          mkdir -p tools
          cp src/rust/rust-toolchain.toml tools/rust-toolchain.toml
      - name: Build wasm package
        uses: r-wasm/actions/build-rwasm@main
        with:
          packages: |
            local::.
