name: format

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup component add rustfmt

      - name: Install `air`
        run: curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sh

      - name: Check formatting in R
        run: air format . --check

      - name: Check formatting in Rust
        run: cargo fmt --all --check --manifest-path src/rust/Cargo.toml
