name: Lint Rust

on:
  pull_request:
    paths:
      - src/rust/**
      - .github/workflows/lint-rust.yml
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/lint-rust.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run cargo fmt
        working-directory: src/rust
        run: |
          rustup component add rustfmt
          cargo fmt --all --check
