name: Lint R

on:
  push:
    branches: [main, master]
    paths:
      - altdoc/**
      - R/**
      - tests/**
      - vignettes/**
  pull_request:
    branches: [main, master]
    paths:
      - altdoc/**
      - R/**
      - tests/**
      - vignettes/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install `air`
        run: curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sh

      - name: Check formatting in R
        run: air format . --check
