name: Test documentation

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-docs.yml
      - altdoc/mkdocs.yml
      - man/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-docs.yml
      - altdoc/mkdocs.yml
      - man/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check missing man pages in mkdocs.yml
        run: |
          YAML_FILE="altdoc/mkdocs.yml"
          FILE_LIST=(man/*.Rd)

          # Track missing files
          missing=0

          for file in "${FILE_LIST[@]}"; do
              base=$(basename "$file" .Rd)
              expected_name="$base.md"

              if ! grep -q "$expected_name" "$YAML_FILE"; then
                  echo "Missing in mkdocs.yml: $expected_name"
                  missing=1
              fi
          done

          if [ "$missing" -ne 0 ]; then
              echo "One or more man pages are not referenced in mkdocs.yml."
              exit 1
          fi

      - name: Check pages in mkdocs.yml that don't exist in "man" folder
        run: |
          YAML_FILE="altdoc/mkdocs.yml"
          missing=0

          while read -r md_path; do
              rd_file="${md_path%.md}.Rd"
              if [ ! -f "$rd_file" ]; then
                  echo "Missing: $rd_file"
                  missing=1
              fi
          done < <(grep -oP 'man/\S+?\.md' "$YAML_FILE")

          # Exit with error if any files are missing
          if [ "$missing" -ne 0 ]; then
              echo "One or more man pages are referenced in mkdocs.yml but don't exist in 'man'."
              exit 1
          fi

      - name: Check no duplicate paths in mkdocs.yml
        run: |
          YAML_FILE="altdoc/mkdocs.yml"
          duplicate=0
          declare -A md_counts

          # Extract man/*.md paths and check for duplicates
          while read -r md_path; do
              ((md_counts["$md_path"]++))
          done < <(grep -o 'man/[^[:space:]]\+\.md' "$YAML_FILE" || true)

          # Report duplicates
          for file in "${!md_counts[@]}"; do
              if [ "${md_counts[$file]}" -gt 1 ]; then
                  echo "Duplicate reference: $file (${md_counts[$file]} times)"
                  duplicate=1
              fi
          done

          # Exit with error if any duplicates were found
          if [ "$duplicate" -ne 0 ]; then
              echo "One or more man pages are duplicated in mkdocs.yml."
              exit 1
          fi
        shell: bash
